MVCeCommerce/Controllers/AlbumController.cs
using MVCeCommerce.Services;
using MVCeCommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCeCommerce.Controllers
{
    public class AlbumController : Controller
    {
        private readonly AlbumDBService albumService = new AlbumDBService();

        // GET: Album
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        #region 相片列表
        [Authorize(Roles = "Admin")]
        public ActionResult List(int Page = 1)
        {
            AlbumViewModel Data = new AlbumViewModel();

            Data.Paging = new ForPaging(Page);
            Data.FileList = albumService.GetDataList(Data.Paging);

            return PartialView(Data);
        }
        #endregion

        #region 上傳檔案
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return PartialView();
        }


        //上傳檔案表單內容用的action
        [Authorize]
        [HttpPost]
        public ActionResult Upload([Bind(Include = "upload")]AlbumViewModel File)
        {
            if(File.upload != null)
            {
                int Alb_Id = albumService.LastAlbumFinder();
                //將檔案和伺服器上路徑合併
                string Url = Path.Combine(Server.MapPath("~/Upload/"), Alb_Id.ToString() + "_" + File.upload.FileName);
                File.upload.SaveAs(Url);

                albumService.UploadFile(Alb_Id, Alb_Id.ToString() + "_" + File.upload.FileName, Url, File.upload.ContentLength, File.upload.ContentType, User.Identity.Name);
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region 顯示圖片
        [Authorize(Roles = "Admin")]
        public ActionResult Show(int Alb_Id)
        {
            AlbumViewModel ToShow = new AlbumViewModel();
            ToShow.File = albumService.GetDataById(Alb_Id);

            if(ToShow.File != null)
            {
                UrlHelper urlHelper = new UrlHelper(Request.RequestContext);
                urlHelper.Content("~/Upload/" + ToShow.File.FileName);

                return Content(urlHelper.Content("~/Upload/" + ToShow.File.FileName));
            }
            else
            {
                return null;
            }
        }
        #endregion

        #region 下載檔案
        [Authorize(Roles = "Admin")]
        public ActionResult DownloadFile(int Alb_Id)
        {
            AlbumViewModel Download = new AlbumViewModel();
            Download.File = albumService.GetDataById(Alb_Id);

            if (Download.File != null)
            {

                Stream iStream = new FileStream(Download.File.Url, FileMode.Open, FileAccess.Read, FileShare.Read);

                return File(iStream, Download.File.Type, Download.File.FileName);
            }
            else
            {
                return JavaScript("alert(\"無此檔案\")");
            }

        }
        #endregion

        #region 刪除檔案
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteFile(int Alb_Id)
        {
            albumService.DeleteArticle(Alb_Id);
            return RedirectToAction("Index");
        }
        #endregion

        #region 相片輪播
        public ActionResult Carousel()
        {
            //宣告一個新頁面模型
            AlbumViewModel Data = new AlbumViewModel();
            //新增頁面模型中的分頁(只顯示第一頁)
            Data.Paging = new ForPaging(1);
            //從Service中取得頁面所需陣列資料
            Data.FileList = albumService.GetDataList(Data.Paging);
            //將頁面資料傳入View中
            return View(Data);
        }
        #endregion
    }
}

MVCeCommerce/Controllers/BlogController.cs
using MVCeCommerce.Models;
using MVCeCommerce.Services;
using MVCeCommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCeCommerce.Controllers
{
    public class BlogController : Controller
    {
        private readonly MembersDBService membersService = new MembersDBService();

        private readonly ArticleDBService articleService = new ArticleDBService();

        private readonly MessageDBService messageService = new MessageDBService();


        #region 開始頁面
        // GET: Blog
        public ActionResult Index(string Account)
        {
            BlogViewModel Data = new BlogViewModel();
            Data.Member = membersService.GetDatabyAccount(Account);
            return View(Data);
        }
        #endregion

        #region 文章列表
        public ActionResult ArticleList(string Search, string Account , int Page = 1)
        {
            ArticleIndexViewModel Data = new ArticleIndexViewModel();
            Data.Search = Search;
            Data.Paging = new ForPaging(Page);
            Data.Account = Account;
            Data.DataList = articleService.GetDataList(Data.Paging, Data.Search, Data.Account);
            return PartialView(Data);

        }
        #endregion

        #region 文章頁面
        public ActionResult Article(int A_Id)
        {
            ArticleViewModel Data = new ArticleViewModel();
            articleService.AddWatch(A_Id);
            Data.article = articleService.GetArticleDataById(A_Id);
            ForPaging Paging = new ForPaging(0);
            Data.DataList = messageService.GetDataList(Paging, A_Id);
            return View(Data);

        }
        #endregion

        #region 新增文章
        [Authorize]
        public ActionResult CreateArticle()
        {
            return PartialView();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateArticle([Bind(Include = "Title, Content")]Article Data)
        {
            Data.Account = User.Identity.Name;
            articleService.InsertArticle(Data);
            return RedirectToAction("Index", new { Account = User.Identity.Name });
        }
        #endregion

        #region 修改文章
        [Authorize]
        public ActionResult EditArticle(int A_Id)
        {
            Article Data = new Article();
            Data = articleService.GetArticleDataById(A_Id);
            return PartialView(Data);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditArticle(int A_Id, Article Data)
        {
            if (articleService.CheckUpdate(A_Id))
            {
                articleService.UpdateArticle(Data);
            }
            return RedirectToAction("Article", new { A_Id = A_Id });
        }
        #endregion


        #region 刪除文章
        [Authorize]
        public ActionResult DeleteArticle(int A_Id)
        {
            articleService.DeleteArticle(A_Id);
            return RedirectToAction("Index", new { Account = User.Identity.Name });
        }
        #endregion

        #region 顯示人氣
        public ActionResult ShowPopularity(string Account)
        {
            ArticleIndexViewModel Data = new ArticleIndexViewModel();
            Data.DataList = articleService.GetPopularList(Account);
            return View(Data);
        }
        #endregion

        #region 留言頁面
        public ActionResult Message(int A_Id = 1)
        {
            ViewData["A_Id"] = A_Id;
            return PartialView();
        }
        #endregion

        #region 留言陣列
        public ActionResult MessageList(int A_Id, int Page = 1)
        {
            MessageViewModel Data = new MessageViewModel();
            Data.Paging = new ForPaging(Page);
            Data.A_Id = A_Id;
            Data.DataList = messageService.GetDataList(Data.Paging, Data.A_Id);
            return PartialView(Data);
        }
        #endregion

        #region 新增留言
        [Authorize]
        public ActionResult CreateMessage(int A_Id)
        {
            ViewData["A_Id"] = A_Id;
            return PartialView();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddMessage(int A_Id, [Bind(Include = "Content")] Message Data)
        {
            Data.A_Id = A_Id;
            Data.Account = User.Identity.Name;
            messageService.InsertMessage(Data);
            return RedirectToAction("MessageList", new { A_Id = A_Id });
        }
        #endregion

        #region 修改留言
        [Authorize]
        public ActionResult UpdateMessage(int A_Id, int M_Id, string Content)
        {
            Message message = new Message();
            message.A_Id = A_Id;
            message.M_Id = M_Id;
            message.Content = Content;
            messageService.UpdateMessage(message);
            return RedirectToAction("Article", new { A_Id = A_Id });
        }
        #endregion

        #region 刪除留言
        [Authorize]
        public ActionResult DeleteMessage(int A_Id, int M_Id)
        {

            messageService.DeleteMessage(A_Id, M_Id);
            return RedirectToAction("Article", new { A_Id = A_Id });
        }
        #endregion
    }
}

MVCeCommerce/Controllers/HomeController.cs
using MVCeCommerce.Services;
using MVCeCommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCeCommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly MembersDBService membersService = new MembersDBService();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult GetDataList(string Search, int Page = 1)
        {
            HomeViewModel Data = new HomeViewModel();
            Data.Search = Search;
            Data.Paging = new ForPaging(Page);
            Data.DataList = membersService.GetDataList(Data.Paging, Data.Search);
            return PartialView(Data);
        }

        [HttpPost]
        public ActionResult GetDataList([Bind(Include ="Search")]HomeViewModel Data)
        {
            return RedirectToAction("GetDataList", new { Search = Data.Search });
        }
    }
}

MVCeCommerce/Controllers/ItemController.cs
using MVCeCommerce.Services;
using MVCeCommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCeCommerce.Controllers
{
    public class ItemController : Controller
    {
        private readonly CartService cartService = new CartService();
        private readonly ItemService itemService = new ItemService();


        // GET: Item
        public ActionResult Index(int Page = 1)
        {
            ItemViewModel Data = new ItemViewModel();
            Data.Paging = new ForPaging(Page);
            Data.IdList = itemService.GetIdList(Data.Paging);
            Data.ItemBlock = new List<ItemDetailViewModel>();

            foreach(var Id in Data.IdList)
            {
                ItemDetailViewModel newBlock = new ItemDetailViewModel();
                newBlock.Data = itemService.GetDataById(Id);
                string Cart = (HttpContext.Session["Cart"] != null) ? HttpContext.Session["Cart"].ToString() : null;

                newBlock.InCart = cartService.CheckInCart(Cart, Id);
                Data.ItemBlock.Add(newBlock);
            }
            return View(Data);
        }

        #region 商品頁面
        public ActionResult Item(int Id)
        {
            ItemDetailViewModel ViewData = new ItemDetailViewModel();
            ViewData.Data = itemService.GetDataById(Id);
            string Cart = (HttpContext.Session["Cart"] != null) ? HttpContext.Session["Cart"].ToString() : null;

            ViewData.InCart = cartService.CheckInCart(Cart, Id);
            return View(ViewData);
        }
        #endregion

        #region 商品列表區塊
        public ActionResult ItemBlock(int Id)
        {
            ItemDetailViewModel ViewData = new ItemDetailViewModel();
            ViewData.Data = itemService.GetDataById(Id);

            string Cart = (HttpContext.Session["Cart"] != null) ? HttpContext.Session["Cart"].ToString() : null;
            ViewData.InCart = cartService.CheckInCart(Cart, Id);
            return PartialView(ViewData);
        }
        #endregion

        #region 新增商品
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Add(ItemCreateViewModel Data)
        {
            if(Data.ItemImage != null)
            {
                string fileName = Path.GetFileName(Data.ItemImage.FileName);
                string Url = Path.Combine(Server.MapPath("~/Upload/"), fileName);
                //將檔案存在伺服器
                Data.ItemImage.SaveAs(Url);
                //設定路徑
                Data.NewData.Image = fileName;
                itemService.Insert(Data.NewData);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("ItemImage", "請選擇上傳檔案");
                return View(Data);

            }
        }
        #endregion

        #region 商品刪除
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int Id)
        {
            itemService.Delete(Id);
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

MVCeCommerce/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCeCommerce/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCeCommerce/Views/Home/GetDataList.cshtml
@model MVCeCommerce.ViewModel.HomeViewModel

<div id="DataList" class="table-responsive">
    <div class="page-header">
        <h1>部落格</h1>
    </div>
    @*建立搜尋文章所須的表單*@
    @using (Ajax.BeginForm("GetDataList", "Home", new AjaxOptions { UpdateTargetId = "DataList" , InsertionMode = InsertionMode.Replace }))
    {
        <div class="col-xs-2 col-md-4 input-group">
            @Html.TextBoxFor(model => model.Search, new { @class = "form-control" })
            <div class="input-group-btn">
                <input class="btn btn-primary " type="submit" value="搜尋" />
            </div>
        </div>
    }
    <table class="table table-hover">
        @*如果資料庫中不是零筆記錄，則顯示資料，並列出新增、刪除與修改連結*@
        @if (!Model.DataList.Count.Equals(0))
        {
            <thead>
                <tr>
                    <th class="text-center">
                        部落格名稱
                    </th>
                    <th class="text-center">
                        作者
                    </th>
                </tr>
            </thead>
            @*將部落格顯示於表格中*@
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td class="text-center">
                        @Html.ActionLink(item.Name, "Index", "Blog", new { Account = item.Account }, null)
                    </td>
                    <td class="text-center">
                        @item.Account
                    </td>
                </tr>
            }
        }
        @*如果資料庫中為零筆記錄，則印出"資料庫內查無資料"*@
        else
        {
            <tr>
                <td colspan="4">
                    尚未有文章
                </td>
            </tr>
        }
    </table>
    @*產生頁碼按鈕*@
    <div class="col-xs-12 text-center">
        <ul class="pagination">
            @*顯示上一頁與最前頁按鈕*@
            <li class="first @((Model.Paging.NowPage > 1) ? "" : " disabled")">
                @Ajax.ActionLink("<<", "GetDataList", new { Page = 1 }, new AjaxOptions { UpdateTargetId = "DataList" , InsertionMode = InsertionMode.Replace })
            </li>
            <li class="pervious @((Model.Paging.NowPage > 1) ? "" : " disabled")">
                @Ajax.ActionLink("<", "GetDataList", new { Page = Model.Paging.NowPage - 1 }, new AjaxOptions { UpdateTargetId = "DataList" ,  InsertionMode = InsertionMode.Replace })
            </li>
            @*顯示各個頁次按鈕*@
            @for (var page = (Model.Paging.NowPage - 6); page < (Model.Paging.NowPage + 6); page++)
            {
                if ((page > 0) && (page <= Model.Paging.MaxPage))
                {
                    if (page == Model.Paging.NowPage)
                    {
                        <li class="active">
                            <a href="#">@page</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            @Ajax.ActionLink(page.ToString(), "GetDataList", new { Page = page }, new AjaxOptions { UpdateTargetId = "DataList"  ,  InsertionMode = InsertionMode.Replace })
                        </li>
                    }
                }
            }
            @*顯示下一頁與最後一頁的按鈕*@
            <li class="next @(((Model.Paging.NowPage < Model.Paging.MaxPage)
        ? "" : " disabled"))">
                @Ajax.ActionLink(">", "GetDataList", new { Page = Model.Paging.NowPage + 1 }, new AjaxOptions { UpdateTargetId = "DataList" , InsertionMode = InsertionMode.Replace })
            </li>
            <li class="last @(((Model.Paging.NowPage < Model.Paging.MaxPage)
        ? "" : " disabled"))">
                @Ajax.ActionLink(">>", "GetDataList", new { Page = Model.Paging.MaxPage }, new AjaxOptions { UpdateTargetId = "DataList" , InsertionMode = InsertionMode.Replace })
            </li>
        </ul>
    </div>
</div>

MVCeCommerce/Views/Home/Index.cshtml
@model MVCeCommerce.ViewModel.HomeViewModel

@{
    ViewBag.Title = "我的購物網站";
}
<style>
    #DataList, #form1 {
        margin-top: 20px;
    }

    .body-content {
        width: 100% !important;
    }

    .btn-default {
        width: 80%;
    }
</style>

@Html.AntiForgeryToken()

@*載入輪播圖頁面*@
@Html.Action("Carousel", "Album", null)

<div id="HomeBlock">
    <div id="LeftBlock" class="col-md-8 col-lg-8 col-sm-8">
        @*載入商品頁面*@
        @Html.Action("Index", "Item", null)
    </div>
    <div id="RightBlock" class="col-md-4 col-lg-4 col-sm-4">
        @*載入資料陣列頁面*@
        @Html.Action("GetDataList")
    </div>
</div>